name: Build sxwm Dynamic Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout uint23/sxwm repository
        uses: actions/checkout@v4
        with:
          repository: uint23/sxwm
          ref: main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            make \
            libx11-dev \
            libxinerama-dev \
            patch

      - name: Modify config.h with custom settings
        run: |
          cat << 'EOF' > config.patch
          --- src/config.h
          +++ src/config.h
          @@ -62,10 +62,12 @@
           * ———————————————————————————————————————————*
           */
           
           CMD(terminal,	"st");
           CMD(browser,	"firefox");
          +CMD(dmenu,	"/home/danrobi/.local/state/nix/profiles/profile/bin/dmenu_run");
          +CMD(background,	"/home/danrobi/.local/state/nix/profiles/profile/bin/feh", "--bg-scale", "/home/danrobi/Good-Pictures/desktop-background-girl.darked.png");
           
           /*
            * ————————————< Keys & Bindins >—————————————*
          @@ -105,7 +107,7 @@
           * ———————————————————————————————————————————*
           */
           
          -/*< This is your modifier key (ALT/SUPER) >*/
          +/*< This is your modifier key (ALT/SUPER) >*/
           #define MOD	ALT
          +#define MOD	Mod4Mask
           
           #include <X11/keysym.h>
           static const Binding binds[] =
          @@ -114,8 +116,9 @@
           
           /*———————< Here are your functions calls >————— — */
           
          -	CALL(MOD|SHIFT,		e,			quit),
          -	CALL(MOD|SHIFT,		q,			close_focused),
          +	BIND(0,			0,			background),
          +	CALL(MOD|ShiftMask,	XK_e,			quit),
          +	CALL(MOD|ShiftMask,	XK_q,			close_focused),
           
          -	CALL(MOD, 		j, 			focus_next),
          -	CALL(MOD, 		k, 			focus_prev),
          +	CALL(MOD,		XK_Left,		focus_next),
          +	CALL(MOD,		XK_Right,		focus_prev),
           
           	CALL(MOD|ShiftMask, 	j, 			move_master_next),
           	CALL(MOD|ShiftMask, 	k, 			move_master_prev),
          @@ -132,6 +135,7 @@
           
           /*—————< Here are your executable functions >—————*/
           
           	BIND(MOD, 		Return,		terminal),
           	BIND(MOD,		b,			browser),
          +	BIND(MOD,		XK_d,			dmenu),
           
           /*—————< This is for workspaces >—————————————————*/
          EOF
          patch -p1 < config.patch || { echo "Patch failed"; cat config.patch; cat src/config.h; exit 1; }

      - name: Check for Makefile and source files
        run: |
          echo "Listing repository contents for debugging:"
          find . -type f
          if [ ! -f Makefile ]; then
            echo "No Makefile found in the repository."
            exit 1
          fi
          if [ ! -f src/sxwm.c ]; then
            echo "Source file src/sxwm.c not found."
            exit 1
          fi
          if [ ! -f src/config.h ]; then
            echo "Configuration file src/config.h not found."
            exit 1
          fi
          echo "Makefile, source files, and config.h found"

      - name: Build sxwm
        run: |
          make
          if [ -f sxwm ]; then
            echo "Binary sxwm found in root"
          elif [ -f src/sxwm ]; then
            echo "Binary sxwm found in src/"
            mv src/sxwm .
          else
            echo "Binary sxwm not found"
            ls -l src/
            exit 1
          fi

      - name: Verify binary
        run: |
          if [ -f sxwm ]; then
            echo "Binary sxwm found"
            file sxwm
            ldd sxwm || true
          else
            echo "Binary sxwm not found"
            ls -l
            exit 1
          fi

      - name: Package binary and source files
        run: |
          mkdir -p artifacts
          cp sxwm artifacts/
          cp -r src artifacts/
          tar -czvf artifacts/sxwm-binary.tar.gz -C artifacts sxwm src

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sxwm-binary
          path: artifacts/sxwm-binary.tar.gz
          retention-days: 7
