name: Build sxwm Dynamic Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout uint23/sxwm repository
        uses: actions/checkout@v4
        with:
          repository: uint23/sxwm
          ref: main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            make \
            libx11-dev \
            libxinerama-dev \
            libxcursor-dev \
            libx11-6 \
            libxinerama1 \
            libxcursor1 \
            patch

      - name: Check for Makefile and source files
        run: |
          echo "Listing repository contents for debugging:"
          find . -type f
          if [ ! -f Makefile ]; then
            echo "No Makefile found in the repository."
            exit 1
          fi
          if [ ! -f src/sxwm.c ]; then
            echo "Source file src/sxwm.c not found."
            exit 1
          fi
          if [ ! -f src/config.h ]; then
            echo "Configuration file src/config.h not found."
            exit 1
          fi
          echo "Makefile, source files, and config.h found"

      - name: Build sxwm
        run: |
          make
          if [ -f sxwm ]; then
            echo "Binary sxwm found in root"
          elif [ -f src/sxwm ]; then
            echo "Binary sxwm found in src/"
            mv src/sxwm .
          else
            echo "Binary sxwm not found"
            ls -l src/
            exit 1
          fi

      - name: Verify binary
        run: |
          if [ -f sxwm ]; then
            echo "Binary sxwm found"
            file sxwm
            ldd sxwm || true
          else
            echo "Binary sxwm not found"
            ls -l
            exit 1
          fi

      - name: Bundle shared libraries
        run: |
          mkdir -p artifacts/lib
          # Copy the binary
          cp sxwm artifacts/
          # Copy source files
          cp -r src artifacts/
          # Copy required shared libraries and their symlinks
          for lib in libXcursor.so.1 libX11.so.6 libXinerama.so.1 libXau.so.6 libXdmcp.so.6 libxcb.so.1; do
            lib_path=$(find /usr/lib /usr/lib64 -name "$lib" -type f -o -type l | head -n 1)
            if [ -n "$lib_path" ]; then
              cp -L "$lib_path" artifacts/lib/
              # Copy the versioned library if it’s a symlink
              real_lib=$(readlink -f "$lib_path")
              if [ "$real_lib" != "$lib_path" ]; then
                cp -L "$real_lib" artifacts/lib/
              fi
            else
              echo "Warning: Library $lib not found"
            fi
          done
          # Create a wrapper script to set LD_LIBRARY_PATH
          cat << 'EOF' > artifacts/run_sxwm.sh
          #!/bin/bash
          SCRIPT_DIR=$(dirname "$(realpath "$0")")
          export LD_LIBRARY_PATH="$SCRIPT_DIR/lib:$LD_LIBRARY_PATH"
          exec "$SCRIPT_DIR/sxwm" "$@"
          EOF
          chmod +x artifacts/run_sxwm.sh
          # List bundled libraries for verification
          echo "Bundled libraries:"
          ls -l artifacts/lib/

      - name: Package binary, source files, and libraries
        run: |
          tar -czvf artifacts/sxwm-binary.tar.gz -C artifacts sxwm src lib run_sxwm.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sxwm-binary
          path: artifacts/sxwm-binary.tar.gz
          retention-days: 7

