name: Build sxwm Dynamic Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            make \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev

      - name: Find Makefile and set working directory
        run: |
          MAKEFILE_DIR=$(find . -type f -name Makefile -exec dirname {} \; | head -n 1)
          if [ -z "$MAKEFILE_DIR" ]; then
            echo "No Makefile found in the repository"
            exit 1
          fi
          echo "Makefile found in $MAKEFILE_DIR"
          echo "MAKEFILE_DIR=$MAKEFILE_DIR" >> $GITHUB_ENV

      - name: Build sxwm
        run: |
          cd $MAKEFILE_DIR
          make
        env:
          MAKEFILE_DIR: ${{ env.MAKEFILE_DIR }}

      - name: Verify binary
        run: |
          cd $MAKEFILE_DIR
          if [ -f sxwm ]; then
            file sxwm
            ldd sxwm || true
          else
            echo "Binary sxwm not found"
            exit 1
          fi
        env:
          MAKEFILE_DIR: ${{ env.MAKEFILE_DIR }}

      - name: Package binary
        run: |
          cd $MAKEFILE_DIR
          mkdir -p artifacts
          cp sxwm artifacts/
          tar -czvf artifacts/sxwm-binary.tar.gz -C artifacts sxwm
        env:
          MAKEFILE_DIR: ${{ env.MAKEFILE_DIR }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sxwm-binary
          path: ${{ env.MAKEFILE_DIR }}/artifacts/sxwm-binary.tar.gz
          retention-days: 7
          
